name: Test sql in actions

on: [push]

jobs:
  test-sql:
    name: Test sql in actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage, localdb
        
      - name: Test sql action
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "CREATE DATABASE test_db"
        
      - name: Read sql command file
        id: sql_command
        uses: andstor/file-reader-action@v1
        with:
          path: "customSQLCommand.sql"

      - name: Execute custom sql command
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "${{ steps.sql_command.outputs.contents }}"
